### ISSUE TITLE
Support Chromium newest versions

### ISSUE THREAD

**Issue by stanislav215** [reg-viz/storycap#896]
From Chromium 128.0.6613.18 version, getting error:

/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:194
            reject(new Error([
                   ^

Error: Failed to launch the browser process!

Related to package: "puppeteer-core": "^9.0.0" in storycap/packages/storycrawler

Please add support.

**Comment by K-kind** [comment]
I encountered a similar issue in my project after the Chrome version of GitHub Actions was updated yesterday. The following error caused Storycap to stop working:

```
TimeoutError: Navigation timeout of 60000 ms exceeded
```

As a temporary solution, it can be fixed using the previous version of Chrome.

```yml
- name: Install Chrome
        id: chrome
        uses: browser-actions/setup-chrome@facf10a55b9caf92e0cc749b4f82bf8220989148 # v1.7.2
        with:
          chrome-version: 127
- name: Take Screenshots
  env:
    CHROME_PATH: ${{ steps.chrome.outputs.chrome-path }}
  run: npm run ci:screenshot
```

package.json

```json
"ci:screenshot": "storycap http://localhost:6007 --chromiumPath $CHROME_PATH --serverCmd 'http-server storybook-static --ci -p 6007'"
```
